{% set name = "device-fingerprinting-pro" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/device_fingerprinting_pro-{{ version }}.tar.gz
  sha256: # Will be filled automatically by conda-forge bot

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - devicefingerprint
  commands:
    - python -c "from devicefingerprint import generate_device_fingerprint; print('Import successful')"
  requires:
    - pip

about:
  home: https://github.com/Johnsonajibi/DeviceFingerprinting
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Professional-grade hardware-based device identification for Python applications
  description: |
    DeviceFingerprint is a comprehensive security library that creates unique, stable 
    identifiers for computing devices by analyzing their hardware characteristics. 
    Built for enterprise security applications, fraud prevention systems, and 
    authentication workflows that demand reliable device recognition.
  doc_url: https://github.com/Johnsonajibi/DeviceFingerprinting#readme
  dev_url: https://github.com/Johnsonajibi/DeviceFingerprinting

extra:
  recipe-maintainers:
    - Johnsonajibi
