name: device-fingerprinting-pro
base: core22
version: '1.0.3'
summary: Professional-grade hardware-based device identification
description: |
  DeviceFingerprint is a comprehensive security library that creates unique, 
  stable identifiers for computing devices by analyzing their hardware 
  characteristics. Built for enterprise security applications, fraud prevention 
  systems, and authentication workflows that demand reliable device recognition.

  Features:
  - Hardware-based device fingerprinting
  - Quantum-resistant cryptography (SHA3-512)
  - Cross-platform support
  - Zero external dependencies
  - Enterprise-ready security features
  - Token binding capabilities

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  device-fingerprinting-pro:
    command: bin/python3 -m devicefingerprint
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages
    plugs:
      - network
      - system-observe
      - hardware-observe

parts:
  device-fingerprinting-pro:
    plugin: python
    source: https://github.com/Johnsonajibi/DeviceFingerprinting.git
    source-type: git
    source-tag: v1.0.3
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3
    python-requirements:
      - device-fingerprinting-pro==1.0.3
