name: Download Statistics Tracking

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual triggers

jobs:
  track-downloads:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Configure tracking
      run: |
        cd tracking
        # Update config with secrets
        python -c "
import json
with open('tracking_config.json', 'r') as f:
    config = json.load(f)
config['github_token'] = '${{ secrets.GITHUB_TOKEN }}'
config['docker_username'] = '${{ secrets.DOCKER_USERNAME }}'
with open('tracking_config.json', 'w') as f:
    json.dump(config, f, indent=2)
"
        
    - name: Run download tracking
      run: |
        cd tracking
        python download_tracker.py
        
    - name: Commit updated statistics
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add tracking/download_stats.csv
        git add tracking/download_report_*.txt
        git diff --staged --quiet || git commit -m "📊 Update download statistics - $(date)"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
