[package]
name = "fingerprint_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "fingerprint_engine"
crate-type = ["cdylib"] # Compile for C-dynamic library

[dependencies]
libc = "0.2"
sha3 = "0.10"
hex = "0.4"
cpufeatures = "0.2"

[build-dependencies]
cbindgen = "0.24"
